import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Invoicer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <head>
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
        <link rel="manifest" href="/site.webmanifest"/>
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5"/>
        <meta name="msapplication-TileColor" content="#4366b0"/>
        <meta name="theme-color" content="#4366b0"/>
      </head>
      <body className={inter.className}>
        {/* light => bg-[#0457D8] bg-gradient-to-tr from-[#0457D8] to-[#4D85B1]    */}
      {/* dark:from-[#204BB4] dark:to-[#7348A5]" */}
        <div className={`flex flex-col justify-between min-h-screen bg-[#0457D8] bg-gradient-to-tr from-[#0457D8] to-[#4D85B1] dark:from-[#204BB4] dark:to-[#7348A5] `}>
          {children}
          {/* <footer className="mu-2 bg-blue-700">
            <div className="max-w-[1200px] mx-auto px-12">
              <h1>Invoicer</h1>
            </div>
          </footer> */}
        </div>
      </body>
    </html>
  );
}
